<h1> Import Libraries/Packages</h1>

In [6]:
import numpy as np
import pandas as pd
import os, sys
import sys




from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score




<h1>Reading the Data Set</h1>

In [7]:
df = pd.read_csv ('parkinsons.data.csv')
#df.head()
df

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0        0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1        0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2        0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3        0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4        0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   
..           ...      ...     ...     ...       ...       ...       ...   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
0    0.266482  2.301442  0.284654  
1    0.335590  2.486855  0.368674  
2    0.311173  2.342259  0.332634  
3    0.334147  2.405554  0.368975  
4    0.234513  2.332180  0.410335  
..        ...       ...       ...  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[195 rows x 24 columns]

<h1>Get Values and Status</h1>

In [8]:
data =df.loc[:,df.columns!='status'].values[:,1:]
labels = df.loc[:,'status'].values
labels
print (data)

[[119.992 157.302 74.997 ... 0.266482 2.3014419999999998 0.284654]
 [122.4 148.65 113.819 ... 0.33559 2.486855 0.368674]
 [116.682 131.111 111.555 ... 0.311173 2.342259 0.33263400000000004]
 ...
 [174.688 240.005 74.287 ... 0.158453 2.6797720000000003
  0.13172799999999998]
 [198.764 396.961 74.904 ... 0.207454 2.138608 0.123306]
 [214.289 260.277 77.973 ... 0.190667 2.555477 0.148569]]


<h1>Count of Diagonsis</h1>

In [9]:
# print(labels[labels==1].shape[0], labels[labels==0].shape[0])
df.groupby('status').size()



status
0     48
1    147
dtype: int64

<h1>Scale the Values to be between -1 and 1</h1>

In [10]:
scaler = MinMaxScaler((-1,1))
x=scaler.fit_transform(data)
y=labels




<h1>Split the Data Set</h1>

In [11]:
x_train,x_test,y_train,y_test = train_test_split (x,y,test_size=0.10,random_state=7)

<h1>Train the Model</h1>

In [12]:
parkinsons_model = XGBClassifier()
history = parkinsons_model.fit(x_train,y_train)


<h1>Prediciting using Test Data </h1>

In [13]:
y_test_Probablity = parkinsons_model.predict_proba(x_test)
y_predict= parkinsons_model.predict(x_test)

for i in range(len(x_test)):
    print("X=%s, Predicted=%s, Decision=%s, Correct Diagonsis=%s" % (x_test[i], y_test_Probablity[i],y_predict[i], y_test[i]))


X=[ 0.41097501 -0.38405136 -0.72351377 -0.74841169 -0.81818182 -0.74662813
 -0.78563773 -0.74634773 -0.67190068 -0.7074774  -0.55739599 -0.70502035
 -0.82234474 -0.55732443 -0.88891365 -0.12980574 -0.18286625 -0.13179765
 -0.36008894 -0.44608853  0.21094744 -0.48488489], Predicted=[0.19047171 0.8095283 ], Decision=1, Correct Diagonsis=0
X=[-0.52719884  0.54139033 -0.73775721 -0.73761118 -0.66007905 -0.83333333
 -0.76205788 -0.83336009 -0.80755888 -0.77649959 -0.84822804 -0.85156038
 -0.84455165 -0.84799076 -0.85453735  0.32504267  0.07884391 -0.12473805
 -0.35676329  0.23209048  0.12368965 -0.55309551], Predicted=[0.07873237 0.9212676 ], Decision=1, Correct Diagonsis=1
X=[-0.12298861 -0.59706462 -0.86985158 -0.63532402 -0.66007905 -0.69942197
 -0.68060021 -0.69947022 -0.8712799  -0.87017256 -0.89098613 -0.89742198
 -0.88084846 -0.89087174 -0.89095076  0.25091441 -0.34030207  0.26050373
 -0.1294314  -0.03373786  0.1289711  -0.28992519], Predicted=[0.01890171 0.9810983 ], Decision=1, Cor

<h1>Accuracy</h1>

In [14]:
print (accuracy_score(y_test, y_predict)*100)

    

95.0


<h1>Comparing Diagnosis<h1>

In [15]:
columns = list(df.columns.values.tolist())
#columns =columns[1:17].append(columns[18:23])
columns.remove('status')
columns.remove('name')

new_data = pd.DataFrame(x_test,columns =columns, index = range(0,20))


#new_data["Doctor Diagnosis"] = y_test

#new_data["Machine Diagonis"]= y_predict

new_data.insert(0,'Doctor Diagnosis',y_test)
new_data.insert(1,'Machine Diagnosis',y_predict)
new_data[['0 PRB','1 PRB']]=pd.DataFrame(y_test_Probablity)

df1 = new_data.pop('1 PRB')
df2 = new_data.pop('0 PRB')

new_data.insert(2,'1 PRB',df1)
new_data.insert(3,'0 PRB',df2)

new_data_visualized = new_data.style.format({"1 PRB":"{:.2%}","0 PRB":"{:.2%}"})
new_data_visualized



<h1>Discrepancy Data</h1>

In [16]:
discrepancy = new_data.loc[(new_data['Doctor Diagnosis'])!=(new_data['Machine Diagnosis'])]
discrepancy

Doctor Diagnosis  Machine Diagnosis     1 PRB     0 PRB  MDVP:Fo(Hz)  \
0                 0                  1  0.809528  0.190472     0.410975   

   MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  MDVP:Jitter(Abs)  MDVP:RAP  \
0     -0.384051     -0.723514       -0.748412         -0.818182 -0.746628   

   ...  MDVP:APQ  Shimmer:DDA       NHR       HNR      RPDE       DFA  \
0  ... -0.822345    -0.557324 -0.888914 -0.129806 -0.182866 -0.131798   

    spread1   spread2        D2       PPE  
0 -0.360089 -0.446089  0.210947 -0.484885  

[1 rows x 26 columns]